version: "3.9"
   
services:
  db:
    container_name: python_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  server:
    build:
      context: ./app-server 
    container_name: python_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./app-server:/var/www
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
    depends_on:
      - db
  client:
    build:
      context: ./app-client
    volumes:
        - ./app-client:/var/www
    container_name: python_client
    command: npm run start
    expose:
          - "3000"
    ports:
      - '3000:3000'
